import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:my_gold_dashboard/Features/order_management/order/order_model.dart';
import 'package:my_gold_dashboard/core/styles/colors.dart';

import '../../Features/returns_managment/data/model/return_model.dart';


List<Widget> buildPageNumbers(int totalPages, int currentPage, void Function(int) goToPage) {
  List<Widget> pageNumbers = [];

  int startPage = 0;
  int endPage = totalPages - 1;

  if (totalPages > 5) {
    if (currentPage <= 2) {
      startPage = 0;
      endPage = 2;
    } else if (currentPage >= totalPages - 3) {
      startPage = totalPages - 3;
      endPage = totalPages - 1;
    } else {
      startPage = currentPage - 1;
      endPage = currentPage + 1;
    }
  }

  for (int i = startPage; i <= endPage; i++) {
    pageNumbers.add(
      GestureDetector(
        onTap: () => goToPage(i),
        child: Container(
          width: 32,
          height: 32,
          margin: const EdgeInsets.symmetric(horizontal: 2),
          decoration: BoxDecoration(
            color: i == currentPage ? AppColors.colorsPrimary2 : Colors.transparent,
            borderRadius: BorderRadius.circular(4),
            border: Border.all(
              color: i == currentPage ? AppColors.colorsPrimary2 : Colors.grey.shade300,
              width: 1,
            ),
          ),
          child: Center(
            child: Text(
              '${i + 1}',
              style: TextStyle(
                color: i == currentPage ? AppColors.colorsSurface : AppColors.colorsText,
                fontWeight: i == currentPage ? FontWeight.w600 : FontWeight.w400,
                fontSize: 14,
              ),
            ),
          ),
        ),
      ),
    );
  }

  return pageNumbers;
}

  
  



List<OrderModel> orders = [
  OrderModel(
    orderId: '#1234',
    customerName: 'Ahmed Al-Sulaiman',
    paymentMethod: 'Cash on Delivery',
    merchant: 'Al-Saab Jewelry',
    product: '100g Gold Bar',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Emergency',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),  OrderModel(
    orderId: '#1234',
    customerName: 'Ahmed Al-Sulaiman',
    paymentMethod: 'Cash on Delivery',
    merchant: 'Al-Saab Jewelry',
    product: '100g Gold Bar',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Emergency',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),  OrderModel(
    orderId: '#1234',
    customerName: 'Ahmed Al-Sulaiman',
    paymentMethod: 'Cash on Delivery',
    merchant: 'Al-Saab Jewelry',
    product: '100g Gold Bar',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Emergency',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),  OrderModel(
    orderId: '#1234',
    customerName: 'Ahmed Al-Sulaiman',
    paymentMethod: 'Cash on Delivery',
    merchant: 'Al-Saab Jewelry',
    product: '100g Gold Bar',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Emergency',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
];


final List<ReturnModel> returnList = [
  ReturnModel(
    returnId: 'R1001',
    orderId: 'O5001',
    customerName: 'Ahmed Hassan',
    reason: 'Damaged item',
    merchant: 'TechWorld',
    date: '2025-06-10',
    orderPic: "https://images.pexels.com/photos/1308881/pexels-photo-1308881.jpeg?cs=srgb&dl=pexels-soldiervip-1308881.jpg&fm=jpg",
    status: 'Pending',
    customerId: 'CUST001',
    receivedDate: '2025-06-09',
    product: 'Wireless Headphones',
    refundDate: '2025-06-15',
    deliveryName: 'FastExpress',
    paymentMethod: 'Credit Card',
    refundStatus: 'Processing',
  ),
  ReturnModel(
    returnId: 'R1002',
    orderId: 'O5002',
    customerName: 'Laila Mostafa',
    reason: 'Wrong size',
    merchant: 'StyleHub',
    date: '2025-06-09',
    orderPic: "https://images.pexels.com/photos/1308881/pexels-photo-1308881.jpeg?cs=srgb&dl=pexels-soldiervip-1308881.jpg&fm=jpg",
    status: 'Approved',
    customerId: 'CUST002',
    receivedDate: '2025-06-08',
    product: 'Denim Jacket',
    refundDate: '2025-06-14',
    deliveryName: 'DHL',
    paymentMethod: 'PayPal',
    refundStatus: 'Completed',
  ),
  ReturnModel(
    returnId: 'R1003',
    orderId: 'O5003',
    customerName: 'Omar Adel',
    reason: 'Late delivery',
    merchant: 'QuickShop',
    date: '2025-06-08',
    orderPic: "https://images.pexels.com/photos/1308881/pexels-photo-1308881.jpeg?cs=srgb&dl=pexels-soldiervip-1308881.jpg&fm=jpg",
    status: 'Rejected',
    customerId: 'CUST003',
    receivedDate: '2025-06-07',
    product: 'Smart Watch',
    refundDate: '2025-06-12',
    deliveryName: 'Aramex',
    paymentMethod: 'Cash on Delivery',
    refundStatus: 'Rejected',
  ),
  ReturnModel(
    returnId: 'R1004',
    orderId: 'O5004',
    customerName: 'Nour Khaled',
    reason: 'Product not as described',
    merchant: 'GadgetMart',
    date: '2025-06-07',
    orderPic: "https://images.pexels.com/photos/1308881/pexels-photo-1308881.jpeg?cs=srgb&dl=pexels-soldiervip-1308881.jpg&fm=jpg",
    status: 'Pending',
    customerId: 'CUST004',
    receivedDate: '2025-06-06',
    product: 'Bluetooth Speaker',
    refundDate: '2025-06-13',
    deliveryName: 'FedEx',
    paymentMethod: 'Visa',
    refundStatus: 'Processing',
  ),
  ReturnModel(
    returnId: 'R1005',
    orderId: 'O5005',
    customerName: 'Youssef Emad',
    reason: 'Ordered by mistake',
    merchant: 'HomeEssentials',
    date: '2025-06-06',
    orderPic: "https://images.pexels.com/photos/1308881/pexels-photo-1308881.jpeg?cs=srgb&dl=pexels-soldiervip-1308881.jpg&fm=jpg",
    status: 'Approved',
    customerId: 'CUST005',
    receivedDate: '2025-06-05',
    product: 'Electric Kettle',
    refundDate: '2025-06-11',
    deliveryName: 'ShipNow',
    paymentMethod: 'MasterCard',
    refundStatus: 'Completed',
  ),

   ReturnModel(
    returnId: 'R1005',
    orderId: 'O5005',
    customerName: 'Youssef Emad',
    reason: 'Ordered by mistake',
    merchant: 'HomeEssentials',
    date: '2025-06-06',
    orderPic: "https://images.pexels.com/photos/1308881/pexels-photo-1308881.jpeg?cs=srgb&dl=pexels-soldiervip-1308881.jpg&fm=jpg",
    status: 'Approved',
    customerId: 'CUST005',
    receivedDate: '2025-06-05',
    product: 'Electric Kettle',
    refundDate: '2025-06-11',
    deliveryName: 'ShipNow',
    paymentMethod: 'MasterCard',
    refundStatus: 'Completed',
  ), ReturnModel(
    returnId: 'R1005',
    orderId: 'O5005',
    customerName: 'Youssef Emad',
    reason: 'Ordered by mistake',
    merchant: 'HomeEssentials',
    date: '2025-06-06',
    orderPic: "https://images.pexels.com/photos/1308881/pexels-photo-1308881.jpeg?cs=srgb&dl=pexels-soldiervip-1308881.jpg&fm=jpg",
    status: 'Approved',
    customerId: 'CUST005',
    receivedDate: '2025-06-05',
    product: 'Electric Kettle',
    refundDate: '2025-06-11',
    deliveryName: 'ShipNow',
    paymentMethod: 'MasterCard',
    refundStatus: 'Completed',
  ), ReturnModel(
    returnId: 'R1005',
    orderId: 'O5005',
    customerName: 'Youssef Emad',
    reason: 'Ordered by mistake',
    merchant: 'HomeEssentials',
    date: '2025-06-06',
    orderPic: "https://images.pexels.com/photos/1308881/pexels-photo-1308881.jpeg?cs=srgb&dl=pexels-soldiervip-1308881.jpg&fm=jpg",
    status: 'Approved',
    customerId: 'CUST005',
    receivedDate: '2025-06-05',
    product: 'Electric Kettle',
    refundDate: '2025-06-11',
    deliveryName: 'ShipNow',
    paymentMethod: 'MasterCard',
    refundStatus: 'Completed',
  ), ReturnModel(
    returnId: 'R1005',
    orderId: 'O5005',
    customerName: 'Youssef Emad',
    reason: 'Ordered by mistake',
    merchant: 'HomeEssentials',
    date: '2025-06-06',
    orderPic: "https://images.pexels.com/photos/1308881/pexels-photo-1308881.jpeg?cs=srgb&dl=pexels-soldiervip-1308881.jpg&fm=jpg",
    status: 'Approved',
    customerId: 'CUST005',
    receivedDate: '2025-06-05',
    product: 'Electric Kettle',
    refundDate: '2025-06-11',
    deliveryName: 'ShipNow',
    paymentMethod: 'MasterCard',
    refundStatus: 'Completed',
  ), ReturnModel(
    returnId: 'R1005',
    orderId: 'O5005',
    customerName: 'Youssef Emad',
    reason: 'Ordered by mistake',
    merchant: 'HomeEssentials',
    date: '2025-06-06',
    orderPic: "https://images.pexels.com/photos/1308881/pexels-photo-1308881.jpeg?cs=srgb&dl=pexels-soldiervip-1308881.jpg&fm=jpg",
    status: 'Approved',
    customerId: 'CUST005',
    receivedDate: '2025-06-05',
    product: 'Electric Kettle',
    refundDate: '2025-06-11',
    deliveryName: 'ShipNow',
    paymentMethod: 'MasterCard',
    refundStatus: 'Completed',
  ), ReturnModel(
    returnId: 'R1005',
    orderId: 'O5005',
    customerName: 'Youssef Emad',
    reason: 'Ordered by mistake',
    merchant: 'HomeEssentials',
    date: '2025-06-06',
    orderPic: "https://images.pexels.com/photos/1308881/pexels-photo-1308881.jpeg?cs=srgb&dl=pexels-soldiervip-1308881.jpg&fm=jpg",
    status: 'Approved',
    customerId: 'CUST005',
    receivedDate: '2025-06-05',
    product: 'Electric Kettle',
    refundDate: '2025-06-11',
    deliveryName: 'ShipNow',
    paymentMethod: 'MasterCard',
    refundStatus: 'Completed',
  ), ReturnModel(
    returnId: 'R1005',
    orderId: 'O5005',
    customerName: 'Youssef Emad',
    reason: 'Ordered by mistake',
    merchant: 'HomeEssentials',
    date: '2025-06-06',
    orderPic: "https://images.pexels.com/photos/1308881/pexels-photo-1308881.jpeg?cs=srgb&dl=pexels-soldiervip-1308881.jpg&fm=jpg",
    status: 'Approved',
    customerId: 'CUST005',
    receivedDate: '2025-06-05',
    product: 'Electric Kettle',
    refundDate: '2025-06-11',
    deliveryName: 'ShipNow',
    paymentMethod: 'MasterCard',
    refundStatus: 'Completed',
  ), ReturnModel(
    returnId: 'R1005',
    orderId: 'O5005',
    customerName: 'Youssef Emad',
    reason: 'Ordered by mistake',
    merchant: 'HomeEssentials',
    date: '2025-06-06',
    orderPic: "https://images.pexels.com/photos/1308881/pexels-photo-1308881.jpeg?cs=srgb&dl=pexels-soldiervip-1308881.jpg&fm=jpg",
    status: 'Approved',
    customerId: 'CUST005',
    receivedDate: '2025-06-05',
    product: 'Electric Kettle',
    refundDate: '2025-06-11',
    deliveryName: 'ShipNow',
    paymentMethod: 'MasterCard',
    refundStatus: 'Completed',
  ), ReturnModel(
    returnId: 'R1005',
    orderId: 'O5005',
    customerName: 'Youssef Emad',
    reason: 'Ordered by mistake',
    merchant: 'HomeEssentials',
    date: '2025-06-06',
    orderPic: "https://images.pexels.com/photos/1308881/pexels-photo-1308881.jpeg?cs=srgb&dl=pexels-soldiervip-1308881.jpg&fm=jpg",
    status: 'Approved',
    customerId: 'CUST005',
    receivedDate: '2025-06-05',
    product: 'Electric Kettle',
    refundDate: '2025-06-11',
    deliveryName: 'ShipNow',
    paymentMethod: 'MasterCard',
    refundStatus: 'Completed',
  ), ReturnModel(
    returnId: 'R1005',
    orderId: 'O5005',
    customerName: 'Youssef Emad',
    reason: 'Ordered by mistake',
    merchant: 'HomeEssentials',
    date: '2025-06-06',
    orderPic: "https://images.pexels.com/photos/1308881/pexels-photo-1308881.jpeg?cs=srgb&dl=pexels-soldiervip-1308881.jpg&fm=jpg",
    status: 'Approved',
    customerId: 'CUST005',
    receivedDate: '2025-06-05',
    product: 'Electric Kettle',
    refundDate: '2025-06-11',
    deliveryName: 'ShipNow',
    paymentMethod: 'MasterCard',
    refundStatus: 'Completed',
  ), ReturnModel(
    returnId: 'R1005',
    orderId: 'O5005',
    customerName: 'Youssef Emad',
    reason: 'Ordered by mistake',
    merchant: 'HomeEssentials',
    date: '2025-06-06',
    orderPic: "https://images.pexels.com/photos/1308881/pexels-photo-1308881.jpeg?cs=srgb&dl=pexels-soldiervip-1308881.jpg&fm=jpg",
    status: 'Approved',
    customerId: 'CUST005',
    receivedDate: '2025-06-05',
    product: 'Electric Kettle',
    refundDate: '2025-06-11',
    deliveryName: 'ShipNow',
    paymentMethod: 'MasterCard',
    refundStatus: 'Completed',
  ), ReturnModel(
    returnId: 'R1005',
    orderId: 'O5005',
    customerName: 'Youssef Emad',
    reason: 'Ordered by mistake',
    merchant: 'HomeEssentials',
    date: '2025-06-06',
    orderPic: "https://images.pexels.com/photos/1308881/pexels-photo-1308881.jpeg?cs=srgb&dl=pexels-soldiervip-1308881.jpg&fm=jpg",
    status: 'Approved',
    customerId: 'CUST005',
    receivedDate: '2025-06-05',
    product: 'Electric Kettle',
    refundDate: '2025-06-11',
    deliveryName: 'ShipNow',
    paymentMethod: 'MasterCard',
    refundStatus: 'Completed',
  ),
];
