import 'package:flutter/material.dart';
import 'package:my_gold_dashboard/Features/order_management/order/order_model.dart';
import 'package:my_gold_dashboard/Features/order_management/widgets/order_managment_table_source.dart';
import 'package:my_gold_dashboard/Features/order_management/widgets/order_table_footer.dart';
import 'package:my_gold_dashboard/core/shared_widget/generic_tables.dart';
import 'package:my_gold_dashboard/core/styles/colors.dart';

class OrdersTable extends StatelessWidget {
  const OrdersTable({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        SingleChildScrollView(
          scrollDirection: Axis.horizontal,
          child: SizedBox(
            height: MediaQuery.sizeOf(context).height * 0.5,
            width: MediaQuery.sizeOf(context).width,
            child: GenericDataTable(
              columns: const [
                "Order ID",
                'Customer Name',
                'Payment Method',
                'Merchant',
                'Product',
                'Order Date',
                'Order State',
                'Actions',
              ],
              source: OrdersDataSource(
                context,
                orders,
                onAccept: () {
                  ScaffoldMessenger.of(context).showSnackBar(
                    SnackBar(
                      content: Text('Order accepted'),
                      backgroundColor: AppColors.trafficLightColorsSuccess,
                    ),
                  );
                },
                onRefuse: () {
                  ScaffoldMessenger.of(context).showSnackBar(
                    SnackBar(
                      content: Text('Order refused'),
                      backgroundColor:AppColors.trafficLightColorsError,
                    ),
                  );
                },
              ),
              rowsPerPage: 6,
            ),
          ),
        ),

       
      ],
    );
  }
}

List<OrderModel> orders = [
  OrderModel(
    orderId: '#1234',
    customerName: 'Ahmed Al-Sulaiman',
    paymentMethod: 'Cash on Delivery',
    merchant: 'Al-Saab Jewelry',
    product: '100g Gold Bar',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Emergency',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),  OrderModel(
    orderId: '#1234',
    customerName: 'Ahmed Al-Sulaiman',
    paymentMethod: 'Cash on Delivery',
    merchant: 'Al-Saab Jewelry',
    product: '100g Gold Bar',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Emergency',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),  OrderModel(
    orderId: '#1234',
    customerName: 'Ahmed Al-Sulaiman',
    paymentMethod: 'Cash on Delivery',
    merchant: 'Al-Saab Jewelry',
    product: '100g Gold Bar',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Emergency',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),  OrderModel(
    orderId: '#1234',
    customerName: 'Ahmed Al-Sulaiman',
    paymentMethod: 'Cash on Delivery',
    merchant: 'Al-Saab Jewelry',
    product: '100g Gold Bar',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Emergency',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
  OrderModel(
    orderId: '#1235',
    customerName: 'Fatima Al-Rashid',
    paymentMethod: 'Credit Card',
    merchant: 'Gold Palace',
    product: 'Gold Necklace',
    orderDate: '24/5/2025 - 3PM',
    orderState: 'Schedule',
  ),
];
